# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/database/v1/data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-google/events/firebase/database/v1/data.proto\x12\"google.events.firebase.database.v1\x1a\x1cgoogle/protobuf/struct.proto\"a\n\x12ReferenceEventData\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Value\x12%\n\x05\x64\x65lta\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueB.\xaa\x02+Google.Events.Protobuf.Firebase.Database.V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.events.firebase.database.v1.data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002+Google.Events.Protobuf.Firebase.Database.V1'
  _REFERENCEEVENTDATA._serialized_start=115
  _REFERENCEEVENTDATA._serialized_end=212
# @@protoc_insertion_point(module_scope)
