# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/pubsub/v1/events.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.events.cloud.pubsub.v1 import data_pb2 as google_dot_events_dot_cloud_dot_pubsub_dot_v1_dot_data__pb2
from google.events import cloudevent_pb2 as google_dot_events_dot_cloudevent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/cloud/pubsub/v1/events.proto',
  package='google.events.cloud.pubsub.v1',
  syntax='proto3',
  serialized_options=b'\252\002&Google.Events.Protobuf.Cloud.PubSub.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*google/events/cloud/pubsub/v1/events.proto\x12\x1dgoogle.events.cloud.pubsub.v1\x1a(google/events/cloud/pubsub/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\x8e\x01\n\x15MessagePublishedEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.pubsub.v1.MessagePublishedData:2\xb2\xf8\xd8,-google.cloud.pubsub.topic.v1.messagePublishedB)\xaa\x02&Google.Events.Protobuf.Cloud.PubSub.V1b\x06proto3'
  ,
  dependencies=[google_dot_events_dot_cloud_dot_pubsub_dot_v1_dot_data__pb2.DESCRIPTOR,google_dot_events_dot_cloudevent__pb2.DESCRIPTOR,])




_MESSAGEPUBLISHEDEVENT = _descriptor.Descriptor(
  name='MessagePublishedEvent',
  full_name='google.events.cloud.pubsub.v1.MessagePublishedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.cloud.pubsub.v1.MessagePublishedEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,-google.cloud.pubsub.topic.v1.messagePublished',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=294,
)

_MESSAGEPUBLISHEDEVENT.fields_by_name['data'].message_type = google_dot_events_dot_cloud_dot_pubsub_dot_v1_dot_data__pb2._MESSAGEPUBLISHEDDATA
DESCRIPTOR.message_types_by_name['MessagePublishedEvent'] = _MESSAGEPUBLISHEDEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessagePublishedEvent = _reflection.GeneratedProtocolMessageType('MessagePublishedEvent', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEPUBLISHEDEVENT,
  '__module__' : 'google.events.cloud.pubsub.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.cloud.pubsub.v1.MessagePublishedEvent)
  })
_sym_db.RegisterMessage(MessagePublishedEvent)


DESCRIPTOR._options = None
_MESSAGEPUBLISHEDEVENT._options = None
# @@protoc_insertion_point(module_scope)
