# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/database/v1/data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/firebase/database/v1/data.proto',
  package='google.events.firebase.database.v1',
  syntax='proto3',
  serialized_options=b'\252\002+Google.Events.Protobuf.Firebase.Database.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-google/events/firebase/database/v1/data.proto\x12\"google.events.firebase.database.v1\x1a\x1cgoogle/protobuf/struct.proto\"a\n\x12ReferenceEventData\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Value\x12%\n\x05\x64\x65lta\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueB.\xaa\x02+Google.Events.Protobuf.Firebase.Database.V1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_REFERENCEEVENTDATA = _descriptor.Descriptor(
  name='ReferenceEventData',
  full_name='google.events.firebase.database.v1.ReferenceEventData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.firebase.database.v1.ReferenceEventData.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delta', full_name='google.events.firebase.database.v1.ReferenceEventData.delta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=212,
)

_REFERENCEEVENTDATA.fields_by_name['data'].message_type = google_dot_protobuf_dot_struct__pb2._VALUE
_REFERENCEEVENTDATA.fields_by_name['delta'].message_type = google_dot_protobuf_dot_struct__pb2._VALUE
DESCRIPTOR.message_types_by_name['ReferenceEventData'] = _REFERENCEEVENTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReferenceEventData = _reflection.GeneratedProtocolMessageType('ReferenceEventData', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCEEVENTDATA,
  '__module__' : 'google.events.firebase.database.v1.data_pb2'
  # @@protoc_insertion_point(class_scope:google.events.firebase.database.v1.ReferenceEventData)
  })
_sym_db.RegisterMessage(ReferenceEventData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
