# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/database/v1/events.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.events.firebase.database.v1 import data_pb2 as google_dot_events_dot_firebase_dot_database_dot_v1_dot_data__pb2
from google.events import cloudevent_pb2 as google_dot_events_dot_cloudevent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/firebase/database/v1/events.proto',
  package='google.events.firebase.database.v1',
  syntax='proto3',
  serialized_options=b'\252\002+Google.Events.Protobuf.Firebase.Database.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/google/events/firebase/database/v1/events.proto\x12\"google.events.firebase.database.v1\x1a-google/events/firebase/database/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\x8b\x01\n\x15ReferenceCreatedEvent\x12\x44\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x36.google.events.firebase.database.v1.ReferenceEventData:,\xb2\xf8\xd8,\'google.firebase.database.ref.v1.created\"\x8b\x01\n\x15ReferenceUpdatedEvent\x12\x44\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x36.google.events.firebase.database.v1.ReferenceEventData:,\xb2\xf8\xd8,\'google.firebase.database.ref.v1.updated\"\x8b\x01\n\x15ReferenceDeletedEvent\x12\x44\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x36.google.events.firebase.database.v1.ReferenceEventData:,\xb2\xf8\xd8,\'google.firebase.database.ref.v1.deleted\"\x8b\x01\n\x15ReferenceWrittenEvent\x12\x44\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x36.google.events.firebase.database.v1.ReferenceEventData:,\xb2\xf8\xd8,\'google.firebase.database.ref.v1.writtenB.\xaa\x02+Google.Events.Protobuf.Firebase.Database.V1b\x06proto3'
  ,
  dependencies=[google_dot_events_dot_firebase_dot_database_dot_v1_dot_data__pb2.DESCRIPTOR,google_dot_events_dot_cloudevent__pb2.DESCRIPTOR,])




_REFERENCECREATEDEVENT = _descriptor.Descriptor(
  name='ReferenceCreatedEvent',
  full_name='google.events.firebase.database.v1.ReferenceCreatedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.firebase.database.v1.ReferenceCreatedEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,\'google.firebase.database.ref.v1.created',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=306,
)


_REFERENCEUPDATEDEVENT = _descriptor.Descriptor(
  name='ReferenceUpdatedEvent',
  full_name='google.events.firebase.database.v1.ReferenceUpdatedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.firebase.database.v1.ReferenceUpdatedEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,\'google.firebase.database.ref.v1.updated',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=448,
)


_REFERENCEDELETEDEVENT = _descriptor.Descriptor(
  name='ReferenceDeletedEvent',
  full_name='google.events.firebase.database.v1.ReferenceDeletedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.firebase.database.v1.ReferenceDeletedEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,\'google.firebase.database.ref.v1.deleted',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=590,
)


_REFERENCEWRITTENEVENT = _descriptor.Descriptor(
  name='ReferenceWrittenEvent',
  full_name='google.events.firebase.database.v1.ReferenceWrittenEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.firebase.database.v1.ReferenceWrittenEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,\'google.firebase.database.ref.v1.written',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=732,
)

_REFERENCECREATEDEVENT.fields_by_name['data'].message_type = google_dot_events_dot_firebase_dot_database_dot_v1_dot_data__pb2._REFERENCEEVENTDATA
_REFERENCEUPDATEDEVENT.fields_by_name['data'].message_type = google_dot_events_dot_firebase_dot_database_dot_v1_dot_data__pb2._REFERENCEEVENTDATA
_REFERENCEDELETEDEVENT.fields_by_name['data'].message_type = google_dot_events_dot_firebase_dot_database_dot_v1_dot_data__pb2._REFERENCEEVENTDATA
_REFERENCEWRITTENEVENT.fields_by_name['data'].message_type = google_dot_events_dot_firebase_dot_database_dot_v1_dot_data__pb2._REFERENCEEVENTDATA
DESCRIPTOR.message_types_by_name['ReferenceCreatedEvent'] = _REFERENCECREATEDEVENT
DESCRIPTOR.message_types_by_name['ReferenceUpdatedEvent'] = _REFERENCEUPDATEDEVENT
DESCRIPTOR.message_types_by_name['ReferenceDeletedEvent'] = _REFERENCEDELETEDEVENT
DESCRIPTOR.message_types_by_name['ReferenceWrittenEvent'] = _REFERENCEWRITTENEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReferenceCreatedEvent = _reflection.GeneratedProtocolMessageType('ReferenceCreatedEvent', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCECREATEDEVENT,
  '__module__' : 'google.events.firebase.database.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.firebase.database.v1.ReferenceCreatedEvent)
  })
_sym_db.RegisterMessage(ReferenceCreatedEvent)

ReferenceUpdatedEvent = _reflection.GeneratedProtocolMessageType('ReferenceUpdatedEvent', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCEUPDATEDEVENT,
  '__module__' : 'google.events.firebase.database.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.firebase.database.v1.ReferenceUpdatedEvent)
  })
_sym_db.RegisterMessage(ReferenceUpdatedEvent)

ReferenceDeletedEvent = _reflection.GeneratedProtocolMessageType('ReferenceDeletedEvent', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCEDELETEDEVENT,
  '__module__' : 'google.events.firebase.database.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.firebase.database.v1.ReferenceDeletedEvent)
  })
_sym_db.RegisterMessage(ReferenceDeletedEvent)

ReferenceWrittenEvent = _reflection.GeneratedProtocolMessageType('ReferenceWrittenEvent', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCEWRITTENEVENT,
  '__module__' : 'google.events.firebase.database.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.firebase.database.v1.ReferenceWrittenEvent)
  })
_sym_db.RegisterMessage(ReferenceWrittenEvent)


DESCRIPTOR._options = None
_REFERENCECREATEDEVENT._options = None
_REFERENCEUPDATEDEVENT._options = None
_REFERENCEDELETEDEVENT._options = None
_REFERENCEWRITTENEVENT._options = None
# @@protoc_insertion_point(module_scope)
