# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/firestore/v1/events.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.events.cloud.firestore.v1 import data_pb2 as google_dot_events_dot_cloud_dot_firestore_dot_v1_dot_data__pb2
from google.events import cloudevent_pb2 as google_dot_events_dot_cloudevent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/cloud/firestore/v1/events.proto',
  package='google.events.cloud.firestore.v1',
  syntax='proto3',
  serialized_options=b'\252\002)Google.Events.Protobuf.Cloud.Firestore.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-google/events/cloud/firestore/v1/events.proto\x12 google.events.cloud.firestore.v1\x1a+google/events/cloud/firestore/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\x8a\x01\n\x14\x44ocumentCreatedEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.firestore.v1.DocumentEventData:/\xb2\xf8\xd8,*google.cloud.firestore.document.v1.created\"\x8a\x01\n\x14\x44ocumentUpdatedEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.firestore.v1.DocumentEventData:/\xb2\xf8\xd8,*google.cloud.firestore.document.v1.updated\"\x8a\x01\n\x14\x44ocumentDeletedEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.firestore.v1.DocumentEventData:/\xb2\xf8\xd8,*google.cloud.firestore.document.v1.deleted\"\x8a\x01\n\x14\x44ocumentWrittenEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.firestore.v1.DocumentEventData:/\xb2\xf8\xd8,*google.cloud.firestore.document.v1.writtenB,\xaa\x02)Google.Events.Protobuf.Cloud.Firestore.V1b\x06proto3'
  ,
  dependencies=[google_dot_events_dot_cloud_dot_firestore_dot_v1_dot_data__pb2.DESCRIPTOR,google_dot_events_dot_cloudevent__pb2.DESCRIPTOR,])




_DOCUMENTCREATEDEVENT = _descriptor.Descriptor(
  name='DocumentCreatedEvent',
  full_name='google.events.cloud.firestore.v1.DocumentCreatedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.cloud.firestore.v1.DocumentCreatedEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,*google.cloud.firestore.document.v1.created',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=299,
)


_DOCUMENTUPDATEDEVENT = _descriptor.Descriptor(
  name='DocumentUpdatedEvent',
  full_name='google.events.cloud.firestore.v1.DocumentUpdatedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.cloud.firestore.v1.DocumentUpdatedEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,*google.cloud.firestore.document.v1.updated',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=440,
)


_DOCUMENTDELETEDEVENT = _descriptor.Descriptor(
  name='DocumentDeletedEvent',
  full_name='google.events.cloud.firestore.v1.DocumentDeletedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.cloud.firestore.v1.DocumentDeletedEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,*google.cloud.firestore.document.v1.deleted',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=581,
)


_DOCUMENTWRITTENEVENT = _descriptor.Descriptor(
  name='DocumentWrittenEvent',
  full_name='google.events.cloud.firestore.v1.DocumentWrittenEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.cloud.firestore.v1.DocumentWrittenEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,*google.cloud.firestore.document.v1.written',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=722,
)

_DOCUMENTCREATEDEVENT.fields_by_name['data'].message_type = google_dot_events_dot_cloud_dot_firestore_dot_v1_dot_data__pb2._DOCUMENTEVENTDATA
_DOCUMENTUPDATEDEVENT.fields_by_name['data'].message_type = google_dot_events_dot_cloud_dot_firestore_dot_v1_dot_data__pb2._DOCUMENTEVENTDATA
_DOCUMENTDELETEDEVENT.fields_by_name['data'].message_type = google_dot_events_dot_cloud_dot_firestore_dot_v1_dot_data__pb2._DOCUMENTEVENTDATA
_DOCUMENTWRITTENEVENT.fields_by_name['data'].message_type = google_dot_events_dot_cloud_dot_firestore_dot_v1_dot_data__pb2._DOCUMENTEVENTDATA
DESCRIPTOR.message_types_by_name['DocumentCreatedEvent'] = _DOCUMENTCREATEDEVENT
DESCRIPTOR.message_types_by_name['DocumentUpdatedEvent'] = _DOCUMENTUPDATEDEVENT
DESCRIPTOR.message_types_by_name['DocumentDeletedEvent'] = _DOCUMENTDELETEDEVENT
DESCRIPTOR.message_types_by_name['DocumentWrittenEvent'] = _DOCUMENTWRITTENEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DocumentCreatedEvent = _reflection.GeneratedProtocolMessageType('DocumentCreatedEvent', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTCREATEDEVENT,
  '__module__' : 'google.events.cloud.firestore.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.cloud.firestore.v1.DocumentCreatedEvent)
  })
_sym_db.RegisterMessage(DocumentCreatedEvent)

DocumentUpdatedEvent = _reflection.GeneratedProtocolMessageType('DocumentUpdatedEvent', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTUPDATEDEVENT,
  '__module__' : 'google.events.cloud.firestore.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.cloud.firestore.v1.DocumentUpdatedEvent)
  })
_sym_db.RegisterMessage(DocumentUpdatedEvent)

DocumentDeletedEvent = _reflection.GeneratedProtocolMessageType('DocumentDeletedEvent', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTDELETEDEVENT,
  '__module__' : 'google.events.cloud.firestore.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.cloud.firestore.v1.DocumentDeletedEvent)
  })
_sym_db.RegisterMessage(DocumentDeletedEvent)

DocumentWrittenEvent = _reflection.GeneratedProtocolMessageType('DocumentWrittenEvent', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTWRITTENEVENT,
  '__module__' : 'google.events.cloud.firestore.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.cloud.firestore.v1.DocumentWrittenEvent)
  })
_sym_db.RegisterMessage(DocumentWrittenEvent)


DESCRIPTOR._options = None
_DOCUMENTCREATEDEVENT._options = None
_DOCUMENTUPDATEDEVENT._options = None
_DOCUMENTDELETEDEVENT._options = None
_DOCUMENTWRITTENEVENT._options = None
# @@protoc_insertion_point(module_scope)
