# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/remoteconfig/v1/data.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/firebase/remoteconfig/v1/data.proto',
  package='google.events.firebase.remoteconfig.v1',
  syntax='proto3',
  serialized_options=b'\252\002/Google.Events.Protobuf.Firebase.RemoteConfig.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1google/events/firebase/remoteconfig/v1/data.proto\x12&google.events.firebase.remoteconfig.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x03\n\x15RemoteConfigEventData\x12\x16\n\x0eversion_number\x18\x01 \x01(\x03\x12/\n\x0bupdate_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12M\n\x0bupdate_user\x18\x03 \x01(\x0b\x32\x38.google.events.firebase.remoteconfig.v1.RemoteConfigUser\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12W\n\rupdate_origin\x18\x05 \x01(\x0e\x32@.google.events.firebase.remoteconfig.v1.RemoteConfigUpdateOrigin\x12S\n\x0bupdate_type\x18\x06 \x01(\x0e\x32>.google.events.firebase.remoteconfig.v1.RemoteConfigUpdateType\x12\x17\n\x0frollback_source\x18\x07 \x01(\x03\"B\n\x10RemoteConfigUser\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t*v\n\x18RemoteConfigUpdateOrigin\x12+\n\'REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED\x10\x00\x12\x0b\n\x07\x43ONSOLE\x10\x01\x12\x0c\n\x08REST_API\x10\x02\x12\x12\n\x0e\x41\x44MIN_SDK_NODE\x10\x03*|\n\x16RemoteConfigUpdateType\x12)\n%REMOTE_CONFIG_UPDATE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12INCREMENTAL_UPDATE\x10\x01\x12\x11\n\rFORCED_UPDATE\x10\x02\x12\x0c\n\x08ROLLBACK\x10\x03\x42\x32\xaa\x02/Google.Events.Protobuf.Firebase.RemoteConfig.V1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_REMOTECONFIGUPDATEORIGIN = _descriptor.EnumDescriptor(
  name='RemoteConfigUpdateOrigin',
  full_name='google.events.firebase.remoteconfig.v1.RemoteConfigUpdateOrigin',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONSOLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REST_API', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADMIN_SDK_NODE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=592,
  serialized_end=710,
)
_sym_db.RegisterEnumDescriptor(_REMOTECONFIGUPDATEORIGIN)

RemoteConfigUpdateOrigin = enum_type_wrapper.EnumTypeWrapper(_REMOTECONFIGUPDATEORIGIN)
_REMOTECONFIGUPDATETYPE = _descriptor.EnumDescriptor(
  name='RemoteConfigUpdateType',
  full_name='google.events.firebase.remoteconfig.v1.RemoteConfigUpdateType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REMOTE_CONFIG_UPDATE_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INCREMENTAL_UPDATE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FORCED_UPDATE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROLLBACK', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=712,
  serialized_end=836,
)
_sym_db.RegisterEnumDescriptor(_REMOTECONFIGUPDATETYPE)

RemoteConfigUpdateType = enum_type_wrapper.EnumTypeWrapper(_REMOTECONFIGUPDATETYPE)
REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED = 0
CONSOLE = 1
REST_API = 2
ADMIN_SDK_NODE = 3
REMOTE_CONFIG_UPDATE_TYPE_UNSPECIFIED = 0
INCREMENTAL_UPDATE = 1
FORCED_UPDATE = 2
ROLLBACK = 3



_REMOTECONFIGEVENTDATA = _descriptor.Descriptor(
  name='RemoteConfigEventData',
  full_name='google.events.firebase.remoteconfig.v1.RemoteConfigEventData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version_number', full_name='google.events.firebase.remoteconfig.v1.RemoteConfigEventData.version_number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='google.events.firebase.remoteconfig.v1.RemoteConfigEventData.update_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_user', full_name='google.events.firebase.remoteconfig.v1.RemoteConfigEventData.update_user', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='google.events.firebase.remoteconfig.v1.RemoteConfigEventData.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_origin', full_name='google.events.firebase.remoteconfig.v1.RemoteConfigEventData.update_origin', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_type', full_name='google.events.firebase.remoteconfig.v1.RemoteConfigEventData.update_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rollback_source', full_name='google.events.firebase.remoteconfig.v1.RemoteConfigEventData.rollback_source', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=522,
)


_REMOTECONFIGUSER = _descriptor.Descriptor(
  name='RemoteConfigUser',
  full_name='google.events.firebase.remoteconfig.v1.RemoteConfigUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.events.firebase.remoteconfig.v1.RemoteConfigUser.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='google.events.firebase.remoteconfig.v1.RemoteConfigUser.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_url', full_name='google.events.firebase.remoteconfig.v1.RemoteConfigUser.image_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=590,
)

_REMOTECONFIGEVENTDATA.fields_by_name['update_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_REMOTECONFIGEVENTDATA.fields_by_name['update_user'].message_type = _REMOTECONFIGUSER
_REMOTECONFIGEVENTDATA.fields_by_name['update_origin'].enum_type = _REMOTECONFIGUPDATEORIGIN
_REMOTECONFIGEVENTDATA.fields_by_name['update_type'].enum_type = _REMOTECONFIGUPDATETYPE
DESCRIPTOR.message_types_by_name['RemoteConfigEventData'] = _REMOTECONFIGEVENTDATA
DESCRIPTOR.message_types_by_name['RemoteConfigUser'] = _REMOTECONFIGUSER
DESCRIPTOR.enum_types_by_name['RemoteConfigUpdateOrigin'] = _REMOTECONFIGUPDATEORIGIN
DESCRIPTOR.enum_types_by_name['RemoteConfigUpdateType'] = _REMOTECONFIGUPDATETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RemoteConfigEventData = _reflection.GeneratedProtocolMessageType('RemoteConfigEventData', (_message.Message,), {
  'DESCRIPTOR' : _REMOTECONFIGEVENTDATA,
  '__module__' : 'google.events.firebase.remoteconfig.v1.data_pb2'
  # @@protoc_insertion_point(class_scope:google.events.firebase.remoteconfig.v1.RemoteConfigEventData)
  })
_sym_db.RegisterMessage(RemoteConfigEventData)

RemoteConfigUser = _reflection.GeneratedProtocolMessageType('RemoteConfigUser', (_message.Message,), {
  'DESCRIPTOR' : _REMOTECONFIGUSER,
  '__module__' : 'google.events.firebase.remoteconfig.v1.data_pb2'
  # @@protoc_insertion_point(class_scope:google.events.firebase.remoteconfig.v1.RemoteConfigUser)
  })
_sym_db.RegisterMessage(RemoteConfigUser)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
