# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/remoteconfig/v1/events.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.events.firebase.remoteconfig.v1 import data_pb2 as google_dot_events_dot_firebase_dot_remoteconfig_dot_v1_dot_data__pb2
from google.events import cloudevent_pb2 as google_dot_events_dot_cloudevent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/firebase/remoteconfig/v1/events.proto',
  package='google.events.firebase.remoteconfig.v1',
  syntax='proto3',
  serialized_options=b'\252\002/Google.Events.Protobuf.Firebase.RemoteConfig.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3google/events/firebase/remoteconfig/v1/events.proto\x12&google.events.firebase.remoteconfig.v1\x1a\x31google/events/firebase/remoteconfig/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\xa2\x01\n\x18RemoteConfigUpdatedEvent\x12K\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32=.google.events.firebase.remoteconfig.v1.RemoteConfigEventData:9\xb2\xf8\xd8,4google.firebase.remoteconfig.remoteConfig.v1.updatedB2\xaa\x02/Google.Events.Protobuf.Firebase.RemoteConfig.V1b\x06proto3'
  ,
  dependencies=[google_dot_events_dot_firebase_dot_remoteconfig_dot_v1_dot_data__pb2.DESCRIPTOR,google_dot_events_dot_cloudevent__pb2.DESCRIPTOR,])




_REMOTECONFIGUPDATEDEVENT = _descriptor.Descriptor(
  name='RemoteConfigUpdatedEvent',
  full_name='google.events.firebase.remoteconfig.v1.RemoteConfigUpdatedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.firebase.remoteconfig.v1.RemoteConfigUpdatedEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,4google.firebase.remoteconfig.remoteConfig.v1.updated',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=341,
)

_REMOTECONFIGUPDATEDEVENT.fields_by_name['data'].message_type = google_dot_events_dot_firebase_dot_remoteconfig_dot_v1_dot_data__pb2._REMOTECONFIGEVENTDATA
DESCRIPTOR.message_types_by_name['RemoteConfigUpdatedEvent'] = _REMOTECONFIGUPDATEDEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RemoteConfigUpdatedEvent = _reflection.GeneratedProtocolMessageType('RemoteConfigUpdatedEvent', (_message.Message,), {
  'DESCRIPTOR' : _REMOTECONFIGUPDATEDEVENT,
  '__module__' : 'google.events.firebase.remoteconfig.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.firebase.remoteconfig.v1.RemoteConfigUpdatedEvent)
  })
_sym_db.RegisterMessage(RemoteConfigUpdatedEvent)


DESCRIPTOR._options = None
_REMOTECONFIGUPDATEDEVENT._options = None
# @@protoc_insertion_point(module_scope)
