# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/analytics/v1/events.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.events.firebase.analytics.v1 import data_pb2 as google_dot_events_dot_firebase_dot_analytics_dot_v1_dot_data__pb2
from google.events import cloudevent_pb2 as google_dot_events_dot_cloudevent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/firebase/analytics/v1/events.proto',
  package='google.events.firebase.analytics.v1',
  syntax='proto3',
  serialized_options=b'\252\002,Google.Events.Protobuf.Firebase.Analytics.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0google/events/firebase/analytics/v1/events.proto\x12#google.events.firebase.analytics.v1\x1a.google/events/firebase/analytics/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\x8e\x01\n\x18\x41nalyticsLogWrittenEvent\x12\x43\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x35.google.events.firebase.analytics.v1.AnalyticsLogData:-\xb2\xf8\xd8,(google.firebase.analytics.log.v1.writtenB/\xaa\x02,Google.Events.Protobuf.Firebase.Analytics.V1b\x06proto3'
  ,
  dependencies=[google_dot_events_dot_firebase_dot_analytics_dot_v1_dot_data__pb2.DESCRIPTOR,google_dot_events_dot_cloudevent__pb2.DESCRIPTOR,])




_ANALYTICSLOGWRITTENEVENT = _descriptor.Descriptor(
  name='AnalyticsLogWrittenEvent',
  full_name='google.events.firebase.analytics.v1.AnalyticsLogWrittenEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.firebase.analytics.v1.AnalyticsLogWrittenEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,(google.firebase.analytics.log.v1.written',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=312,
)

_ANALYTICSLOGWRITTENEVENT.fields_by_name['data'].message_type = google_dot_events_dot_firebase_dot_analytics_dot_v1_dot_data__pb2._ANALYTICSLOGDATA
DESCRIPTOR.message_types_by_name['AnalyticsLogWrittenEvent'] = _ANALYTICSLOGWRITTENEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalyticsLogWrittenEvent = _reflection.GeneratedProtocolMessageType('AnalyticsLogWrittenEvent', (_message.Message,), {
  'DESCRIPTOR' : _ANALYTICSLOGWRITTENEVENT,
  '__module__' : 'google.events.firebase.analytics.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.firebase.analytics.v1.AnalyticsLogWrittenEvent)
  })
_sym_db.RegisterMessage(AnalyticsLogWrittenEvent)


DESCRIPTOR._options = None
_ANALYTICSLOGWRITTENEVENT._options = None
# @@protoc_insertion_point(module_scope)
