# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/v1/data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/firebase/v1/data.proto',
  package='google.events.firebase.v1',
  syntax='proto3',
  serialized_options=b'\252\002\"Google.Events.Protobuf.Firebase.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$google/events/firebase/v1/data.proto\x12\x19google.events.firebase.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe2\x01\n\x11\x44ocumentEventData\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Value\x12%\n\x05\x64\x65lta\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value\x12N\n\twildcards\x18\x03 \x03(\x0b\x32;.google.events.firebase.v1.DocumentEventData.WildcardsEntry\x1a\x30\n\x0eWildcardsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42%\xaa\x02\"Google.Events.Protobuf.Firebase.V1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_DOCUMENTEVENTDATA_WILDCARDSENTRY = _descriptor.Descriptor(
  name='WildcardsEntry',
  full_name='google.events.firebase.v1.DocumentEventData.WildcardsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='google.events.firebase.v1.DocumentEventData.WildcardsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='google.events.firebase.v1.DocumentEventData.WildcardsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=324,
)

_DOCUMENTEVENTDATA = _descriptor.Descriptor(
  name='DocumentEventData',
  full_name='google.events.firebase.v1.DocumentEventData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.firebase.v1.DocumentEventData.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delta', full_name='google.events.firebase.v1.DocumentEventData.delta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wildcards', full_name='google.events.firebase.v1.DocumentEventData.wildcards', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DOCUMENTEVENTDATA_WILDCARDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=324,
)

_DOCUMENTEVENTDATA_WILDCARDSENTRY.containing_type = _DOCUMENTEVENTDATA
_DOCUMENTEVENTDATA.fields_by_name['data'].message_type = google_dot_protobuf_dot_struct__pb2._VALUE
_DOCUMENTEVENTDATA.fields_by_name['delta'].message_type = google_dot_protobuf_dot_struct__pb2._VALUE
_DOCUMENTEVENTDATA.fields_by_name['wildcards'].message_type = _DOCUMENTEVENTDATA_WILDCARDSENTRY
DESCRIPTOR.message_types_by_name['DocumentEventData'] = _DOCUMENTEVENTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DocumentEventData = _reflection.GeneratedProtocolMessageType('DocumentEventData', (_message.Message,), {

  'WildcardsEntry' : _reflection.GeneratedProtocolMessageType('WildcardsEntry', (_message.Message,), {
    'DESCRIPTOR' : _DOCUMENTEVENTDATA_WILDCARDSENTRY,
    '__module__' : 'google.events.firebase.v1.data_pb2'
    # @@protoc_insertion_point(class_scope:google.events.firebase.v1.DocumentEventData.WildcardsEntry)
    })
  ,
  'DESCRIPTOR' : _DOCUMENTEVENTDATA,
  '__module__' : 'google.events.firebase.v1.data_pb2'
  # @@protoc_insertion_point(class_scope:google.events.firebase.v1.DocumentEventData)
  })
_sym_db.RegisterMessage(DocumentEventData)
_sym_db.RegisterMessage(DocumentEventData.WildcardsEntry)


DESCRIPTOR._options = None
_DOCUMENTEVENTDATA_WILDCARDSENTRY._options = None
# @@protoc_insertion_point(module_scope)
