# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/scheduler/v1/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n+google/events/cloud/scheduler/v1/data.proto\x12 google.events.cloud.scheduler.v1\"'\n\x10SchedulerJobData\x12\x13\n\x0b\x63ustom_data\x18\x01 \x01(\x0c\x42,\xaa\x02)Google.Events.Protobuf.Cloud.Scheduler.V1b\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "google.events.cloud.scheduler.v1.data_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\252\002)Google.Events.Protobuf.Cloud.Scheduler.V1"
    )
    _SCHEDULERJOBDATA._serialized_start = 81
    _SCHEDULERJOBDATA._serialized_end = 120
# @@protoc_insertion_point(module_scope)
