# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/pubsub/v1/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n(google/events/cloud/pubsub/v1/data.proto\x12\x1dgoogle.events.cloud.pubsub.v1\x1a\x1fgoogle/protobuf/timestamp.proto"k\n\x14MessagePublishedData\x12=\n\x07message\x18\x01 \x01(\x0b\x32,.google.events.cloud.pubsub.v1.PubsubMessage\x12\x14\n\x0csubscription\x18\x02 \x01(\t"\xfe\x01\n\rPubsubMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12P\n\nattributes\x18\x02 \x03(\x0b\x32<.google.events.cloud.pubsub.v1.PubsubMessage.AttributesEntry\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\x30\n\x0cpublish_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cordering_key\x18\x05 \x01(\t\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42)\xaa\x02&Google.Events.Protobuf.Cloud.PubSub.V1b\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "google.events.cloud.pubsub.v1.data_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\252\002&Google.Events.Protobuf.Cloud.PubSub.V1"
    _PUBSUBMESSAGE_ATTRIBUTESENTRY._options = None
    _PUBSUBMESSAGE_ATTRIBUTESENTRY._serialized_options = b"8\001"
    _MESSAGEPUBLISHEDDATA._serialized_start = 108
    _MESSAGEPUBLISHEDDATA._serialized_end = 215
    _PUBSUBMESSAGE._serialized_start = 218
    _PUBSUBMESSAGE._serialized_end = 472
    _PUBSUBMESSAGE_ATTRIBUTESENTRY._serialized_start = 423
    _PUBSUBMESSAGE_ATTRIBUTESENTRY._serialized_end = 472
# @@protoc_insertion_point(module_scope)
