# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/scheduler/v1/data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/cloud/scheduler/v1/data.proto',
  package='google.events.cloud.scheduler.v1',
  syntax='proto3',
  serialized_options=b'\252\002)Google.Events.Protobuf.Cloud.Scheduler.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+google/events/cloud/scheduler/v1/data.proto\x12 google.events.cloud.scheduler.v1\"\'\n\x10SchedulerJobData\x12\x13\n\x0b\x63ustom_data\x18\x01 \x01(\x0c\x42,\xaa\x02)Google.Events.Protobuf.Cloud.Scheduler.V1b\x06proto3'
)




_SCHEDULERJOBDATA = _descriptor.Descriptor(
  name='SchedulerJobData',
  full_name='google.events.cloud.scheduler.v1.SchedulerJobData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='custom_data', full_name='google.events.cloud.scheduler.v1.SchedulerJobData.custom_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['SchedulerJobData'] = _SCHEDULERJOBDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SchedulerJobData = _reflection.GeneratedProtocolMessageType('SchedulerJobData', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULERJOBDATA,
  '__module__' : 'google.events.cloud.scheduler.v1.data_pb2'
  # @@protoc_insertion_point(class_scope:google.events.cloud.scheduler.v1.SchedulerJobData)
  })
_sym_db.RegisterMessage(SchedulerJobData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
