# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/scheduler/v1/events.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.events.cloud.scheduler.v1 import data_pb2 as google_dot_events_dot_cloud_dot_scheduler_dot_v1_dot_data__pb2
from google.events import cloudevent_pb2 as google_dot_events_dot_cloudevent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/cloud/scheduler/v1/events.proto',
  package='google.events.cloud.scheduler.v1',
  syntax='proto3',
  serialized_options=b'\252\002)Google.Events.Protobuf.Cloud.Scheduler.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-google/events/cloud/scheduler/v1/events.proto\x12 google.events.cloud.scheduler.v1\x1a+google/events/cloud/scheduler/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\x81\x01\n\x10JobExecutedEvent\x12@\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x32.google.events.cloud.scheduler.v1.SchedulerJobData:+\xb2\xf8\xd8,&google.cloud.scheduler.job.v1.executedB,\xaa\x02)Google.Events.Protobuf.Cloud.Scheduler.V1b\x06proto3'
  ,
  dependencies=[google_dot_events_dot_cloud_dot_scheduler_dot_v1_dot_data__pb2.DESCRIPTOR,google_dot_events_dot_cloudevent__pb2.DESCRIPTOR,])




_JOBEXECUTEDEVENT = _descriptor.Descriptor(
  name='JobExecutedEvent',
  full_name='google.events.cloud.scheduler.v1.JobExecutedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.cloud.scheduler.v1.JobExecutedEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,&google.cloud.scheduler.job.v1.executed',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=290,
)

_JOBEXECUTEDEVENT.fields_by_name['data'].message_type = google_dot_events_dot_cloud_dot_scheduler_dot_v1_dot_data__pb2._SCHEDULERJOBDATA
DESCRIPTOR.message_types_by_name['JobExecutedEvent'] = _JOBEXECUTEDEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobExecutedEvent = _reflection.GeneratedProtocolMessageType('JobExecutedEvent', (_message.Message,), {
  'DESCRIPTOR' : _JOBEXECUTEDEVENT,
  '__module__' : 'google.events.cloud.scheduler.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.cloud.scheduler.v1.JobExecutedEvent)
  })
_sym_db.RegisterMessage(JobExecutedEvent)


DESCRIPTOR._options = None
_JOBEXECUTEDEVENT._options = None
# @@protoc_insertion_point(module_scope)
