# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/storage/v1/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n)google/events/cloud/storage/v1/data.proto\x12\x1egoogle.events.cloud.storage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x08\n\x11StorageObjectData\x12\x18\n\x10\x63ontent_encoding\x18\x01 \x01(\t\x12\x1b\n\x13\x63ontent_disposition\x18\x02 \x01(\t\x12\x15\n\rcache_control\x18\x03 \x01(\t\x12\x18\n\x10\x63ontent_language\x18\x05 \x01(\t\x12\x16\n\x0emetageneration\x18\x06 \x01(\x03\x12\x30\n\x0ctime_deleted\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x63ontent_type\x18\x08 \x01(\t\x12\x0c\n\x04size\x18\t \x01(\x03\x12\x30\n\x0ctime_created\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x63rc32c\x18\x0b \x01(\t\x12\x17\n\x0f\x63omponent_count\x18\x0c \x01(\x05\x12\x10\n\x08md5_hash\x18\r \x01(\t\x12\x0c\n\x04\x65tag\x18\x0e \x01(\t\x12+\n\x07updated\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rstorage_class\x18\x10 \x01(\t\x12\x14\n\x0ckms_key_name\x18\x11 \x01(\t\x12>\n\x1atime_storage_class_updated\x18\x12 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0etemporary_hold\x18\x13 \x01(\x08\x12=\n\x19retention_expiration_time\x18\x14 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12Q\n\x08metadata\x18\x15 \x03(\x0b\x32?.google.events.cloud.storage.v1.StorageObjectData.MetadataEntry\x12\x18\n\x10\x65vent_based_hold\x18\x1d \x01(\x08\x12\x0c\n\x04name\x18\x17 \x01(\t\x12\n\n\x02id\x18\x18 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x19 \x01(\t\x12\x12\n\ngeneration\x18\x1a \x01(\x03\x12\x61\n\x13\x63ustomer_encryption\x18\x1c \x01(\x0b\x32\x44.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption\x12\x12\n\nmedia_link\x18\x64 \x01(\t\x12\x11\n\tself_link\x18\x65 \x01(\t\x12\x0c\n\x04kind\x18\x66 \x01(\t\x1a\x46\n\x12\x43ustomerEncryption\x12\x1c\n\x14\x65ncryption_algorithm\x18\x01 \x01(\t\x12\x12\n\nkey_sha256\x18\x02 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42*\xaa\x02'Google.Events.Protobuf.Cloud.Storage.V1b\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "google.events.cloud.storage.v1.data_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\252\002'Google.Events.Protobuf.Cloud.Storage.V1"
    _STORAGEOBJECTDATA_METADATAENTRY._options = None
    _STORAGEOBJECTDATA_METADATAENTRY._serialized_options = b"8\001"
    _STORAGEOBJECTDATA._serialized_start = 111
    _STORAGEOBJECTDATA._serialized_end = 1152
    _STORAGEOBJECTDATA_CUSTOMERENCRYPTION._serialized_start = 1033
    _STORAGEOBJECTDATA_CUSTOMERENCRYPTION._serialized_end = 1103
    _STORAGEOBJECTDATA_METADATAENTRY._serialized_start = 1105
    _STORAGEOBJECTDATA_METADATAENTRY._serialized_end = 1152
# @@protoc_insertion_point(module_scope)
