# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/audit/v1/events.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.events.cloud.audit.v1 import data_pb2 as google_dot_events_dot_cloud_dot_audit_dot_v1_dot_data__pb2
from google.events import cloudevent_pb2 as google_dot_events_dot_cloudevent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/cloud/audit/v1/events.proto',
  package='google.events.cloud.audit.v1',
  syntax='proto3',
  serialized_options=b'\252\002%Google.Events.Protobuf.Cloud.Audit.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)google/events/cloud/audit/v1/events.proto\x12\x1cgoogle.events.cloud.audit.v1\x1a\'google/events/cloud/audit/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"x\n\x14\x41uditLogWrittenEvent\x12\x38\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32*.google.events.cloud.audit.v1.AuditLogData:&\xb2\xf8\xd8,!google.cloud.audit.log.v1.writtenB(\xaa\x02%Google.Events.Protobuf.Cloud.Audit.V1b\x06proto3'
  ,
  dependencies=[google_dot_events_dot_cloud_dot_audit_dot_v1_dot_data__pb2.DESCRIPTOR,google_dot_events_dot_cloudevent__pb2.DESCRIPTOR,])




_AUDITLOGWRITTENEVENT = _descriptor.Descriptor(
  name='AuditLogWrittenEvent',
  full_name='google.events.cloud.audit.v1.AuditLogWrittenEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.events.cloud.audit.v1.AuditLogWrittenEvent.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\262\370\330,!google.cloud.audit.log.v1.written',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=268,
)

_AUDITLOGWRITTENEVENT.fields_by_name['data'].message_type = google_dot_events_dot_cloud_dot_audit_dot_v1_dot_data__pb2._AUDITLOGDATA
DESCRIPTOR.message_types_by_name['AuditLogWrittenEvent'] = _AUDITLOGWRITTENEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuditLogWrittenEvent = _reflection.GeneratedProtocolMessageType('AuditLogWrittenEvent', (_message.Message,), {
  'DESCRIPTOR' : _AUDITLOGWRITTENEVENT,
  '__module__' : 'google.events.cloud.audit.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:google.events.cloud.audit.v1.AuditLogWrittenEvent)
  })
_sym_db.RegisterMessage(AuditLogWrittenEvent)


DESCRIPTOR._options = None
_AUDITLOGWRITTENEVENT._options = None
# @@protoc_insertion_point(module_scope)
