# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/storage/v1/data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/events/cloud/storage/v1/data.proto',
  package='google.events.cloud.storage.v1',
  syntax='proto3',
  serialized_options=b'\252\002\'Google.Events.Protobuf.Cloud.Storage.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)google/events/cloud/storage/v1/data.proto\x12\x1egoogle.events.cloud.storage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x08\n\x11StorageObjectData\x12\x18\n\x10\x63ontent_encoding\x18\x01 \x01(\t\x12\x1b\n\x13\x63ontent_disposition\x18\x02 \x01(\t\x12\x15\n\rcache_control\x18\x03 \x01(\t\x12\x18\n\x10\x63ontent_language\x18\x05 \x01(\t\x12\x16\n\x0emetageneration\x18\x06 \x01(\x03\x12\x30\n\x0ctime_deleted\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x63ontent_type\x18\x08 \x01(\t\x12\x0c\n\x04size\x18\t \x01(\x03\x12\x30\n\x0ctime_created\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x63rc32c\x18\x0b \x01(\t\x12\x17\n\x0f\x63omponent_count\x18\x0c \x01(\x05\x12\x10\n\x08md5_hash\x18\r \x01(\t\x12\x0c\n\x04\x65tag\x18\x0e \x01(\t\x12+\n\x07updated\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rstorage_class\x18\x10 \x01(\t\x12\x14\n\x0ckms_key_name\x18\x11 \x01(\t\x12>\n\x1atime_storage_class_updated\x18\x12 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0etemporary_hold\x18\x13 \x01(\x08\x12=\n\x19retention_expiration_time\x18\x14 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12Q\n\x08metadata\x18\x15 \x03(\x0b\x32?.google.events.cloud.storage.v1.StorageObjectData.MetadataEntry\x12\x18\n\x10\x65vent_based_hold\x18\x1d \x01(\x08\x12\x0c\n\x04name\x18\x17 \x01(\t\x12\n\n\x02id\x18\x18 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x19 \x01(\t\x12\x12\n\ngeneration\x18\x1a \x01(\x03\x12\x61\n\x13\x63ustomer_encryption\x18\x1c \x01(\x0b\x32\x44.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption\x12\x12\n\nmedia_link\x18\x64 \x01(\t\x12\x11\n\tself_link\x18\x65 \x01(\t\x1a\x46\n\x12\x43ustomerEncryption\x12\x1c\n\x14\x65ncryption_algorithm\x18\x01 \x01(\t\x12\x12\n\nkey_sha256\x18\x02 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42*\xaa\x02\'Google.Events.Protobuf.Cloud.Storage.V1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_STORAGEOBJECTDATA_CUSTOMERENCRYPTION = _descriptor.Descriptor(
  name='CustomerEncryption',
  full_name='google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='encryption_algorithm', full_name='google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.encryption_algorithm', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_sha256', full_name='google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.key_sha256', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1019,
  serialized_end=1089,
)

_STORAGEOBJECTDATA_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='google.events.cloud.storage.v1.StorageObjectData.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='google.events.cloud.storage.v1.StorageObjectData.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='google.events.cloud.storage.v1.StorageObjectData.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1091,
  serialized_end=1138,
)

_STORAGEOBJECTDATA = _descriptor.Descriptor(
  name='StorageObjectData',
  full_name='google.events.cloud.storage.v1.StorageObjectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_encoding', full_name='google.events.cloud.storage.v1.StorageObjectData.content_encoding', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_disposition', full_name='google.events.cloud.storage.v1.StorageObjectData.content_disposition', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cache_control', full_name='google.events.cloud.storage.v1.StorageObjectData.cache_control', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_language', full_name='google.events.cloud.storage.v1.StorageObjectData.content_language', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metageneration', full_name='google.events.cloud.storage.v1.StorageObjectData.metageneration', index=4,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_deleted', full_name='google.events.cloud.storage.v1.StorageObjectData.time_deleted', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_type', full_name='google.events.cloud.storage.v1.StorageObjectData.content_type', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='google.events.cloud.storage.v1.StorageObjectData.size', index=7,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_created', full_name='google.events.cloud.storage.v1.StorageObjectData.time_created', index=8,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crc32c', full_name='google.events.cloud.storage.v1.StorageObjectData.crc32c', index=9,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='component_count', full_name='google.events.cloud.storage.v1.StorageObjectData.component_count', index=10,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='md5_hash', full_name='google.events.cloud.storage.v1.StorageObjectData.md5_hash', index=11,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='etag', full_name='google.events.cloud.storage.v1.StorageObjectData.etag', index=12,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated', full_name='google.events.cloud.storage.v1.StorageObjectData.updated', index=13,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='storage_class', full_name='google.events.cloud.storage.v1.StorageObjectData.storage_class', index=14,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kms_key_name', full_name='google.events.cloud.storage.v1.StorageObjectData.kms_key_name', index=15,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_storage_class_updated', full_name='google.events.cloud.storage.v1.StorageObjectData.time_storage_class_updated', index=16,
      number=18, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temporary_hold', full_name='google.events.cloud.storage.v1.StorageObjectData.temporary_hold', index=17,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='retention_expiration_time', full_name='google.events.cloud.storage.v1.StorageObjectData.retention_expiration_time', index=18,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='google.events.cloud.storage.v1.StorageObjectData.metadata', index=19,
      number=21, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_based_hold', full_name='google.events.cloud.storage.v1.StorageObjectData.event_based_hold', index=20,
      number=29, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='google.events.cloud.storage.v1.StorageObjectData.name', index=21,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='google.events.cloud.storage.v1.StorageObjectData.id', index=22,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bucket', full_name='google.events.cloud.storage.v1.StorageObjectData.bucket', index=23,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generation', full_name='google.events.cloud.storage.v1.StorageObjectData.generation', index=24,
      number=26, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='customer_encryption', full_name='google.events.cloud.storage.v1.StorageObjectData.customer_encryption', index=25,
      number=28, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='media_link', full_name='google.events.cloud.storage.v1.StorageObjectData.media_link', index=26,
      number=100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='self_link', full_name='google.events.cloud.storage.v1.StorageObjectData.self_link', index=27,
      number=101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STORAGEOBJECTDATA_CUSTOMERENCRYPTION, _STORAGEOBJECTDATA_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=1138,
)

_STORAGEOBJECTDATA_CUSTOMERENCRYPTION.containing_type = _STORAGEOBJECTDATA
_STORAGEOBJECTDATA_METADATAENTRY.containing_type = _STORAGEOBJECTDATA
_STORAGEOBJECTDATA.fields_by_name['time_deleted'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STORAGEOBJECTDATA.fields_by_name['time_created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STORAGEOBJECTDATA.fields_by_name['updated'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STORAGEOBJECTDATA.fields_by_name['time_storage_class_updated'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STORAGEOBJECTDATA.fields_by_name['retention_expiration_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STORAGEOBJECTDATA.fields_by_name['metadata'].message_type = _STORAGEOBJECTDATA_METADATAENTRY
_STORAGEOBJECTDATA.fields_by_name['customer_encryption'].message_type = _STORAGEOBJECTDATA_CUSTOMERENCRYPTION
DESCRIPTOR.message_types_by_name['StorageObjectData'] = _STORAGEOBJECTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StorageObjectData = _reflection.GeneratedProtocolMessageType('StorageObjectData', (_message.Message,), {

  'CustomerEncryption' : _reflection.GeneratedProtocolMessageType('CustomerEncryption', (_message.Message,), {
    'DESCRIPTOR' : _STORAGEOBJECTDATA_CUSTOMERENCRYPTION,
    '__module__' : 'google.events.cloud.storage.v1.data_pb2'
    # @@protoc_insertion_point(class_scope:google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption)
    })
  ,

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _STORAGEOBJECTDATA_METADATAENTRY,
    '__module__' : 'google.events.cloud.storage.v1.data_pb2'
    # @@protoc_insertion_point(class_scope:google.events.cloud.storage.v1.StorageObjectData.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _STORAGEOBJECTDATA,
  '__module__' : 'google.events.cloud.storage.v1.data_pb2'
  # @@protoc_insertion_point(class_scope:google.events.cloud.storage.v1.StorageObjectData)
  })
_sym_db.RegisterMessage(StorageObjectData)
_sym_db.RegisterMessage(StorageObjectData.CustomerEncryption)
_sym_db.RegisterMessage(StorageObjectData.MetadataEntry)


DESCRIPTOR._options = None
_STORAGEOBJECTDATA_METADATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
