# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test Library Generation
on:
  pull_request:
    paths:
      - "scripts/**"
      - ".github/workflows/test_generation.yaml"

jobs:
  test-generator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      LIBRARY_CHECKOUT_PATH: library
      DATA_SOURCE_CHECKOUT_PATH: google-cloudevents

    steps:
      - name: Python Library > Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.LIBRARY_CHECKOUT_PATH }}

      - name: Proto Schemas > Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: googleapis/google-cloudevents
          path: ${{ env.DATA_SOURCE_CHECKOUT_PATH }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Generator Dependencies
        working-directory: ${{ env.LIBRARY_CHECKOUT_PATH }}
        run: pip install -r ./scripts/requirements.txt

      - name: Run the generator
        working-directory: ${{ env.LIBRARY_CHECKOUT_PATH }}
        run: python ./scripts/generate-from-proto.py -o ./src --quiet

      - name: Run library tests
        working-directory: ${{ env.LIBRARY_CHECKOUT_PATH }}
        env:
          GOOGLE_EVENTS_TESTDATA: ../${{env.DATA_SOURCE_CHECKOUT_PATH}}/testdata
        run: |
          pip install -r requirements-dev.txt
          pip install ./src
          pytest -v .

      - name: View generator output
        if: ${{ always() }}
        working-directory: ${{ env.LIBRARY_CHECKOUT_PATH }}
        run: |
          git add -N . # Needed if files are untracked
          git diff --ignore-all-space --ignore-blank-lines
